import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="min-h-screen" style={{ background: "linear-gradient(135deg, #C7D0C8, #DCE2DC)" }}>
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="bg-card rounded-[28px] p-8 sm:p-12 shadow-2xl">
          <h1 className="text-3xl font-extrabold text-white mb-2">Terms of Service</h1>
          <p className="text-sm font-medium mb-8" style={{ color: "#8A8A8A" }}>
            Last updated: June 2026
          </p>

          <div className="space-y-8 text-sm leading-relaxed" style={{ color: "#ccc" }}>
            <section>
              <h2 className="text-lg font-bold text-white mb-3">1. Acceptance</h2>
              <p>
                By using AI Job Apply, you agree to these Terms of Service. If you do not agree,
                do not use the application.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">2. Description of Service</h2>
              <p>
                AI Job Apply is an AI-assisted tool that helps users draft tailored job application
                emails using their resume and job descriptions. It sends emails through the user&apos;s
                own Gmail account via the Gmail API.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">3. User Responsibilities</h2>
              <ul className="list-disc list-inside space-y-2">
                <li>You are responsible for the accuracy of your resume and application content.</li>
                <li>You must use the app only for legitimate job application purposes.</li>
                <li>You must not use the app to send spam, mass unsolicited emails, or any content that violates applicable laws.</li>
                <li>You are responsible for keeping your account secure.</li>
                <li>You must not share your account credentials with others.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">4. AI-Generated Content</h2>
              <p>
                Email drafts are generated by third-party LLM providers. AI-generated content may
                contain inaccuracies. You are responsible for reviewing and editing all generated
                emails before sending. We do not guarantee the accuracy or quality of AI outputs.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">5. Service Limitations</h2>
              <ul className="list-disc list-inside space-y-2">
                <li>We do not guarantee job placement or interview outcomes.</li>
                <li>The app depends on third-party APIs (Google, LLM providers) which may experience downtime.</li>
                <li>We reserve the right to modify or discontinue the service at any time.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">6. Account Termination</h2>
              <p>
                You may delete your account at any time from the app settings. We may suspend or
                terminate accounts that violate these terms. Upon termination, your data will be
                deleted in accordance with our Privacy Policy.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">7. Limitation of Liability</h2>
              <p>
                AI Job Apply is provided &quot;as is&quot; without warranties of any kind. We are not
                liable for any damages arising from the use of this application, including but not
                limited to lost job opportunities, data loss, or unauthorized access.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">8. Changes to Terms</h2>
              <p>
                We may update these terms from time to time. Continued use of the app after changes
                constitutes acceptance of the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-3">9. Contact</h2>
              <p>
                For questions about these terms, contact us at{" "}
                <a href="mailto:pranavdileep10@gmail.com" className="text-primary-custom underline">
                  pranavdileep10@gmail.com
                </a>.
              </p>
            </section>
          </div>

          <div className="mt-10 pt-6" style={{ borderTop: "1px solid #1e1e1e" }}>
            <Link href="/" className="text-primary-custom text-sm font-bold hover:underline">
              &larr; Back to App
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
